### ISSUE TITLE
Project still in development?

### ISSUE THREAD

**Issue by rue-a** [kgeographer/geojson-t#4]
Hi, 

I'd be interested in what the current state of the project is. While it apparently had some uptake, it kind of seems abandoned now. At least, it appears to have not resolved in a specification. Or is it considered finished as is?

With a target group of digital humanists with no background in geosciences in mind, I wonder, if I should rather recommend to use JSON-FG, despite it being way more complex and (as I understand) not covering all time related features that this extension offers. 

Cheers Arne

**Comment by rue-a** [comment]
Ok, I just read that it was superseded by the LinkedPlacesFormat. Maybe you could mention that at the top of the README.

**Comment by kgeographer** [comment]
Hello Arne,
Very sorry for the trouble; I've updated the README. Yes, GeoJSON-T evolved to become Linked Places format (LPF), for use particularly in the [World Historical Gazetteer project](https://whgazetteer.org), and has seen increasing uptake by other projects in the last couple years. I hadn't seen latest developments of JSON-FG - LPF goes further with support for temporality, and a somewhat different direction, with most extension elements outside the "properties" one.
-kg

**Comment by rue-a** [comment]
Thank you, I like how it turned out in LPF.
